package com.crudspring.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.hateoas.RepresentationModel;

@Entity
@Table(name = "team")
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(value = "Team Model V2")

public class TeamV2 extends RepresentationModel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter
    @Setter
    @ApiModelProperty(notes = "The ID, auto generated by database", required = true)
    private long id;

    @Column(name = "team_name", nullable = false, length = 30)
    @Getter @Setter
    private String teamName;

    @Column(name = "create_year", nullable = false, length = 4)
    @Getter @Setter
    private String createYear;

    // new cptional columns of V2

    @Column(name = "team_awards", length = 30)
    @Getter @Setter
    private String teamAwards;

    @Column(name = "team_nickname", length = 30)
    @Getter @Setter
    private String teamNickname;

    @Column(name = "team_city", length = 30)
    @Getter @Setter
    private String teamCity;

    // including relationship with league

    @ManyToOne
    @JoinColumn(name = "league_id")
    @Getter @Setter
    private League league;
}