insert into league (league_name, country_name) values ('Vivyan', 'United States');
insert into league (league_name, country_name) values ('Alfons', 'Indonesia');
insert into league (league_name, country_name) values ('Stefan', 'China');
insert into league (league_name, country_name) values ('Modesty', 'Indonesia');
insert into league (league_name, country_name) values ('Johnathon', 'Brazil');
insert into league (league_name, country_name) values ('Ingamar', 'Japan');
insert into league (league_name, country_name) values ('Astrix', 'Norway');
insert into league (league_name, country_name) values ('Rossy', 'China');
insert into league (league_name, country_name) values ('Adella', 'United States');
insert into league (league_name, country_name) values ('Zenia', 'Mexico');
insert into league (league_name, country_name) values ('Annabal', 'China');
insert into league (league_name, country_name) values ('Drona', 'Ghana');
insert into league (league_name, country_name) values ('Paulette', 'Indonesia');
insert into league (league_name, country_name) values ('Mitzi', 'China');
insert into league (league_name, country_name) values ('Thoma', 'Azerbaijan');
insert into league (league_name, country_name) values ('Nani', 'Portugal');
insert into league (league_name, country_name) values ('Dorian', 'France');
insert into league (league_name, country_name) values ('Freemon', 'Czech Republic');
insert into league (league_name, country_name) values ('Allyson', 'Cambodia');
insert into league (league_name, country_name) values ('Issie', 'Argentina');
insert into league (league_name, country_name) values ('Tammi', 'Philippines');
insert into league (league_name, country_name) values ('Domingo', 'Indonesia');
insert into league (league_name, country_name) values ('Ned', 'Ukraine');
insert into league (league_name, country_name) values ('Theodor', 'China');
insert into league (league_name, country_name) values ('Edsel', 'Poland');
insert into league (league_name, country_name) values ('Abner', 'France');
insert into league (league_name, country_name) values ('Hayward', 'Syria');
insert into league (league_name, country_name) values ('Kaleena', 'Indonesia');
insert into league (league_name, country_name) values ('Vivia', 'China');
insert into league (league_name, country_name) values ('Moise', 'Guam');
insert into league (league_name, country_name) values ('Orran', 'Indonesia');
insert into league (league_name, country_name) values ('Gwyn', 'Indonesia');
insert into league (league_name, country_name) values ('Leora', 'Brazil');
insert into league (league_name, country_name) values ('Luciana', 'Indonesia');
insert into league (league_name, country_name) values ('Barb', 'Honduras');
insert into league (league_name, country_name) values ('Aile', 'Indonesia');
insert into league (league_name, country_name) values ('Windham', 'Iran');
insert into league (league_name, country_name) values ('Almeda', 'Yemen');
insert into league (league_name, country_name) values ('Gal', 'Cayman Islands');
insert into league (league_name, country_name) values ('Clara', 'Peru');
insert into league (league_name, country_name) values ('Elke', 'China');
insert into league (league_name, country_name) values ('Erick', 'Portugal');
insert into league (league_name, country_name) values ('Uta', 'Czech Republic');
insert into league (league_name, country_name) values ('Hagan', 'Norway');
insert into league (league_name, country_name) values ('Lilith', 'China');
insert into league (league_name, country_name) values ('Julee', 'China');
insert into league (league_name, country_name) values ('Erich', 'China');
insert into league (league_name, country_name) values ('Hermon', 'China');
insert into league (league_name, country_name) values ('Grissel', 'Panama');
insert into league (league_name, country_name) values ('Pennie', 'Indonesia');