insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Noni', 7819, 'Viva', 'Panevėžys Air Base', 'Borzechów', 22);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Nadiya', 3561, 'Tin', 'Rafael Cabrera Airport', 'Không', 10);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Abigail', 7942, 'Alpha', 'Al Wajh Domestic Airport', 'Ronggo', 4);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Noelle', 8797, 'Voyatouch', 'Port Gentil Airport', 'Djohong', 26);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Kaela', 1269, 'Zontrax', 'Mahanoro Airport', 'Las Flores', 11);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Homerus', 2476, 'Tempsoft', 'West Angelas Airport', 'Kortesjärvi', 50);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Bud', 8551, 'Transcof', 'Biała Podlaska Airfield', 'Khlong Luang', 15);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Gilli', 9782, 'Voyatouch', 'Aboisso Airport', 'Huangbei', 18);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Mercy', 795, 'Otcom', 'Tuuta Airport', 'Lantera', 36);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Drusilla', 1110, 'Hatity', 'El Hadj Airport', 'Isulan', 27);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Immanuel', 7251, 'Andalax', 'Flugplatz Güttin / Rügen', 'Derzhavīnsk', 18);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Hyacinthia', 1280, 'Cardguard', 'Agostinho Neto Airport', 'Sumbermanggis', 31);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Petra', 4241, 'Treeflex', 'Málaga Airport', 'Kingston', 46);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Dev', 5804, 'Stringtough', 'Laramie Regional Airport', 'Les Cèdres', 42);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Tomkin', 3654, 'Bytecard', 'Thomasville Regional Airport', 'Ljungby', 13);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Robinetta', 419, 'Stringtough', 'Gaoua Airport', 'Zheleznnyy', 15);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Tulley', 8246, 'Konklux', 'Madang Airport', 'Krzyżanowice', 15);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Zak', 9835, 'Lotstring', 'Girdwood Airport', 'Shuanggang', 35);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Maxie', 3775, 'Regrant', 'Aribinda Airport', 'Fotolívos', 4);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Rice', 1329, 'Overhold', 'Benalla Airport', 'Phu Kam Yao', 22);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Hansiain', 9175, 'Zathin', 'Toowoomba Airport', 'Wonda', 41);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Tybalt', 7684, 'Treeflex', 'Lenawee County Airport', 'Samaipata', 23);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Obed', 319, 'Holdlamis', 'Wrotham Park Airport', 'Bandong', 49);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Veriee', 3208, 'Flexidy', 'Kolwezi Airport', 'Cikadoa', 42);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Liv', 884, 'Quo Lux', 'Dimbokro Airport', 'Binitayan', 39);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Bobine', 5361, 'Voyatouch', 'Fazenda Bela Vista Airport', 'Sukojember', 19);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Alfy', 7062, 'Sonsing', 'Winisk Airport', 'Vargem Grande', 50);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Addy', 9177, 'Alphazap', 'International Airport', 'Xinghe Chenggu', 34);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Bent', 88, 'Wrapsafe', 'Metro Field', 'Xinan', 39);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Yolanda', 9562, 'Bigtax', 'Ramechhap Airport', 'Sharga', 18);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Rourke', 8806, 'Andalax', 'Teminabuan Airport', 'Fengping', 20);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Katine', 4984, 'Span', 'Kavanayen Airport', 'Krajan Pundungsari', 43);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Maybelle', 1696, 'Cardguard', 'Maxwell Air Force Base', 'Agualote', 3);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Teresita', 5723, 'Gembucket', 'North Bird Field', 'Simo', 19);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Christoffer', 695, 'Sonair', 'Guaratinguetá Airport', 'Seixal', 25);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Clive', 9893, 'Aerified', 'Daocheng Yading Airport', 'Vicente Guerrero', 41);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Fiorenze', 593, 'Cardify', 'Fairview Airport', 'Marvdasht', 33);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Missie', 6585, 'Y-find', 'Adana Airport', 'Cilampuyang', 33);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Aloysius', 4037, 'Quo Lux', 'Macaé Airport', 'Suwon-si', 50);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Guinevere', 6539, 'Transcof', 'Inc Airport', 'Gammad', 21);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Marcelia', 9289, 'Keylex', 'Berdyansk Airport', 'Mamfe', 34);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Had', 7025, 'Ventosanzap', 'Franklin County Airport', 'Hat Yai', 14);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Emmie', 8322, 'Keylex', 'Erzincan Airport', 'Araçoiaba da Serra', 44);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Geri', 3433, 'Prodder', 'Kalgoorlie Boulder Airport', 'Jamālpur', 1);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Jojo', 8551, 'Konklab', 'Amy Airport', 'Wangon', 45);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Constance', 2006, 'Keylex', 'Leopoldina Airport', 'Topdac', 5);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Clive', 2984, 'Bitchip', 'Ar Horqin Airport', 'Geita', 8);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Henka', 4396, 'Zontrax', 'Elenak Airport', 'Leran Kulon', 13);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Emilia', 5887, 'Ronstring', 'Garça Airport', 'Yuanba', 12);
insert into team (team_name, create_year, team_awards, team_nickname, team_city, league_id) values ('Modestine', 1186, 'Solarbreeze', 'Okierabu Airport', 'Seongnam-si', 41);